## Criando Matriz

In [2]:
# Importando o módulo NumPy
import numpy as np

In [3]:
# Criando uma matriz
matriz = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
print(matriz)

[[1 2 3]
 [4 5 6]]


In [5]:
matriz.shape

(2, 3)

In [6]:
# Criando uma matriz 2x3 apenas com números "1"
matriz1 = np.ones((2, 3))

In [7]:
print(matriz1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Criando uma matriz a partir de uma lista de listas
lista = [[13, 14, 15], [16, 17, 18], [19, 20, 21]]

In [9]:
# A função matriz cria uma matriz a partir de uma sequência
matriz2 = np.matrix(lista)

In [10]:
print(matriz2)

[[13 14 15]
 [16 17 18]
 [19 20 21]]


In [11]:
type(matriz2)

numpy.matrixlib.defmatrix.matrix

In [12]:
# Formato da matriz
np.shape(matriz2)

(3, 3)

In [13]:
matriz2.size

9

In [14]:
matriz2.dtype

dtype('int32')

In [15]:
matriz2.itemsize # tamanho que será ocupado na memória do computador

4

In [16]:
matriz2.nbytes

36

In [17]:
matriz2[2, 1]

20

In [18]:
# Alterando um elemento da matriz
matriz2[1, 0] = 100

In [19]:
matriz2

matrix([[ 13,  14,  15],
        [100,  17,  18],
        [ 19,  20,  21]])

In [20]:
x = np.array([1, 2]) # NumPy decide o tipo dos dados
y = np.array([1.0, 2.0]) # NumPy decide o tipo dos dados
z = np.array([1, 2], dtype = np.float64) # Forçamos um tipo de dados em particular

print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [23]:
matriz3 = np.array([[24, 76], [35, 89]], dtype=float)

In [24]:
matriz3

array([[24., 76.],
       [35., 89.]])

In [25]:
matriz3.itemsize

8

In [26]:
matriz3.nbytes

32

In [27]:
matriz3.ndim

2

In [28]:
matriz3[1, 1]

89.0

In [29]:
matriz3[1, 1] = 100

In [30]:
matriz3

array([[ 24.,  76.],
       [ 35., 100.]])