## Outras Operações com Arrays

In [2]:
# Importando o NumPy
import numpy as np

In [3]:
# Slicing
a = np.diag(np.arange(3))

In [4]:
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [5]:
a[1, 1]

1

In [6]:
a[1]

array([0, 1, 0])

In [7]:
b = np.arange(10)

In [8]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# [start:end:step]
b[2:9:3]

array([2, 5, 8])

In [10]:
# Comparação
a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])
a == b

array([False, False, False, False])

In [11]:
np.array_equal(a, b)

False

In [12]:
a.min()

1

In [13]:
a.max()

4

In [14]:
# Somando um elemento ao array
np.array([1, 2, 3]) + 1.5

array([2.5, 3.5, 4.5])

In [15]:
# Usando o método around
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [16]:
b = np.around(a)

In [17]:
b

array([1., 2., 2., 2., 4., 4.])

In [18]:
# Criando um array
b = np.array([1, 2, 3, 4])

In [19]:
b

array([1, 2, 3, 4])

In [20]:
# Copiando um array
c = b.flatten()

In [21]:
c

array([1, 2, 3, 4])

In [22]:
# Criando um array
v = np.array([1, 2, 3])

In [23]:
# Adicionando uma dimensão ao array
v[:, np.newaxis], v[:, np.newaxis].shape, v[np.newaxis, :].shape

(array([[1],
        [2],
        [3]]), (3, 1), (1, 3))

In [24]:
# Repetindo os elementos de um array
np.repeat(v, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [25]:
# Repetindo os elementos de um array
np.tile(v, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
# Criando um array
w = np.array([5, 6])

In [27]:
w

array([5, 6])

In [28]:
# Concatenando 
np.concatenate((v, w), axis=0)

array([1, 2, 3, 5, 6])

In [29]:
# Copiando arrays
r = np.copy(v)

In [30]:
r

array([1, 2, 3])